### PR TITLE
Add Sinhala locale and file

### PR DESCRIPTION
**Pull request by magdalenajadach**

### CODE REVIEW

**Review by Jonic — COMMENTED** [review]
Dev bit looks good. Awaiting content approval, then we can merge :)

**Comment by ninaszymor** [comment]
`hint_title` is OK
`save` should say: ඔබගේ ව්‍යාපෘතිය සුරකින්න

**Comment by magdalenajadach** [comment]
@ninaszymor Updated as requested!

**Comment by ninaszymor** [comment]
Looks good now.

**Pull request merged**
