### PR TITLE
Added and updated translations (#62)

### PR DESCRIPTION
**Pull request by sra405**
* Update kn-IN.yml

* Update el-GR.yml

* Update zh-TW.yml

* Add files via upload

* Add files via upload

* Update sr-SP.yml

* Add files via upload

* Add files via upload

* Add files via upload

* Update cy-GB.yml

* Update locales/no-NO.yml

---------

### CODE REVIEW

**Comment by conorriches** [comment]
For some inexplicable reason the Norwegian key of `no` causes the tests to break. ~Looking at whether we can change this to `no-NO` - @sra405 do you think doing this change would break something else?~

**Comment by conorriches** [comment]
I've set the Norwegian key to have quotes around the key as this should prevent `no` being parsed as something else. If this works with other repos then great! If not we may need to update the key! :)

**Comment by sra405** [comment]
> I've set the Norwegian key to have quotes around the key as this should prevent `no` being parsed as something else. If this works with other repos then great! If not we may need to update the key! :)

Great spot!! I'm not overly convinced these two character locales will work correctly but there seems to be a fair few of them (in more specific locale files 😅). We can go back and fix that if its a problem though 👍

**Comment by sra405** [comment]
annoyingly I can't approve so I'll just merge up 😄

**Pull request merged**
