### PR TITLE
Update markup

### PR DESCRIPTION
**Pull request by Jonic**
This enables the kramdown plugin to generate markup compatible with the work in: https://github.com/RaspberryPiFoundation/slash-learning-ui/pull/182

### CODE REVIEW

**Comment by aldreth** [comment]
@Jonic Failing tests :(

**Comment by Jonic** [comment]
Hmm. They all passed on my machine. Will check them again and update this PR tomorrow :)

**Comment by Jonic** [comment]
@aldreth Now that tests are passing can I get another review here please? Then if you're happy I'll bump the version number and do the release tasks, and then update it on UPS.

**Review by aldreth — APPROVED** [review]
:shipit:

**Comment by aldreth** [comment]
@Jonic When you update UPS, will you also make sure that you update the js to make sure hints/ingredients still work. https://github.com/RaspberryPiFoundation/ups/blob/265558d10a0dc68842812d9e4f7b6dd0eeba04ff/app/assets/javascripts/application.js

**Pull request merged**
