### PR TITLE
v0.5.0

### PR DESCRIPTION
**Pull request by Jonic**
Enables code block with optional filenames.

## Input

```
--- code ---
---
filename: ./assets/scss/application.scss
---
[ code goes here ]
--- /code ---
```
## Output:

```html
<div class="c-code">
  <div class="c-code__filename">
    ./assets/scss/application.scss
  </div>

  <div class="c-code__content">
    <pre><code class="language-bash">mkdir whoopee
cd whoopee
wget http://rpf.io/burp -O burp.wav
aplay burp.wav
</code></pre>
  </div>
</div>
```

The filename value is optional, and currently the resulting HTML has no styles. Next step will be to get this in use on production so I can then start working on the front-end angle.

### CODE REVIEW

**Comment by aldreth** [comment]
@Jonic I am anxious about enclosing code blocks in `--- code ---` syntax - I think it'll be too easy to come to depend on this for styling, which will then force content editors to update all exisiting projects. 

Could we do something very similar, but just for the filename 
```
--- code-filename ---
ruby.rb
--- /code-filename ---
```
and rely on it being placed next to a codeblock by the content team, producing markup a bit like this:

```
<div class="c-code__filename">
    ./assets/scss/application.scss
</div>
<pre><code class="language-bash">mkdir whoopee
cd whoopee
wget http://rpf.io/burp -O burp.wav
aplay burp.wav
</code></pre>
```

What do you think?

**Comment by Jonic** [comment]
@aldreth We could do it like that, yeah. I just thought that having some more markup around the code blocks would give us some more flexibility in styling. Coderay generates an awful mess of mangled HTML and styles that isn't easy to work with, but I guess the correct solution there is to not use Coderay, or anything at all with a website that looks as bad as this: http://coderay.rubychan.de/

Shall I make the change, then? It won't take any time at all, really.

**Comment by aldreth** [comment]
@Jonic If we don't like the markup produced by coderay, kramdown also supports rouge https://kramdown.gettalong.org/syntax_highlighter/rouge.html, it'd be an easy switch if you want to have a look at what that produces.

I agree the extra markup would give us more flexibility - but I think we'd come to rely on it! So if you could change that'd be great. 😄

**Comment by Jonic** [comment]
@aldreth Gotcha. I'll get this updated.

I also didn't know about Rouge. Shall I take a look at that as well and see if making that switch would benefit us? It won't result in any changes to the existing markdown, so hopefully it'll be painless so long as I've got styles in place. I've always wanted to get rid of Coderay! Since I'm working on updates to code blocks maybe this is a good time to do that?

**Comment by aldreth** [comment]
@Jonic Yes - feel free to have a look at rouge here too.

**Comment by Jonic** [comment]
@aldreth I've update the code_filename thing. Shall we get this one merged and I'll sort out rouge this afternoon?

**Pull request closed without merging**
