### PR TITLE
Remove all references to challenges

### PR DESCRIPTION
**Pull request by Jonic**

### CODE REVIEW

**Comment by Jonic** [comment]
@martinohanlon Hey Martin, this PR remove the bit of our Markdown parsing tool that converts the `--- challenge ---` delimeters. We're not going to deploy it until we've got the signal from the content team that there are none of the old delimeters in any of the projects. Rik's off today, so I wondered if you perhaps knew if there were any?

If there are, let us know when they've been removed, and we can deploy this change. Ta!

**Comment by martinohanlon** [comment]
I have added the removal of `--- challenge ---` tags to the activities we need to complete when migrating projects - this activity will be a longer term task though so we will have to park this PR for a little while.

**Comment by Jonic** [comment]
@martinohanlon Thanks for that. We can even merge this PR, we just can't update the version on projects-admin to use this version. Now that we know you've got it on your to-do list we can merge this safely without breaking anything, but there's no rush!

**Review by aldreth — APPROVED** [review]

**Comment by martinohanlon** [comment]
Is the implication of merging this that if we need to make any change to a project we will have to remove the --- challenge -- tags before we promote to master?

**Comment by Jonic** [comment]
@martinohanlon No. The implication of merging this right now is nothing. The version of this plugin that's still in use on projects-admin is tagged at `0.6.0`, which is not going to change to this version (`0.7.0`) until the old delimeters are no longer in the content. So we'll merge this, but it won't change anything until we're ready to bump the version on projects-admin.

**Pull request merged**
